capitalizeListTitles = false
copyright = "AGPL-3.0-or-later"
disableKinds = ["taxonomy", "term"]
enableGitInfo = true
enableRobotsTXT = true
languageCode = "en"
noChmod = true
noTimes = true
pluralizeListTitles = false
printUnusedTemplates = true
templateMetrics = true
templateMetricsHints = true
timeout = "60s"
timeZone = "UTC"
title = "7m45h"

[build]
noJSConfigInAssets = true
useResourceCacheWhen = "always"
[build.buildStats]
enable = true

[minify]
minifyOutput = true
[minify.tdewolff.css]
keepCSS2 = false
[minify.tdewolff.html]
keepDefaultAttrVals = false
keepQuotes = true
[minify.tdewolff.js]
version = 0
[minify.tdewolff.json]
keepNumbers = true

[params]
author = "tmash"
src = "https://github.com/7m45h/www_7m45h/tree/master/"

[security]
enableInlineShortcodes = true

[sitemap]
changefreq = "weekly"
