# baseURL                = ""
capitalizeListTitles   = false
cleanDestinationDir    = true
defaultContentLanguage = "en-us"
copyright              = "AGPL-3.0 license"
disableKinds           = [ "rss", "taxonomy", "term" ]
enableGitInfo          = true
enableRobotsTXT        = true
languageCode           = "en-us"
noChmod                = true
noTimes                = true
pluralizeListTitles    = false
removePathAccents      = true
timeout                = "1m"
timeZone               = "UTC"
title                  = "7m45h"
titleCaseStyle         = nan
ignoreFiles            = ['\.bck'] # ignore helix .bck files

[build]
noJSConfigInAssets   = true
useResourceCacheWhen = "always"
[build.buildStats]
enable = true

[minify]
minifyOutput = true
[minify.tdewolff.css]
keepCSS2 = false
[minify.tdewolff.html]
keepQuotes = true
[minify.tdewolff.js]
version = 0
[minify.tdewolff.json]
keepNumbers = true

[security]
enableInlineShortcodes = true

[sitemap]
changeFreq = "weekly"

[params]
author    = "tmash"
gitremote = "https://codeberg.org/7m45h/www_7m45h/"
