capitalizeListTitles = false
copyright = "AGPL-3.0-or-later"
disableKinds = ["taxonomy", "term"]
enableGitInfo = true
languageCode = "en"
noChmod = true
noTimes = true
pluralizeListTitles = false
printUnusedTemplates = true
templateMetrics = true
templateMetricsHints = true
timeout = "60s"
timeZone = "UTC"
title = "7m45h"

[build]
useResourceCacheWhen = "always"
[build.buildStats]
enable = true

[mediaTypes]
[mediaTypes."application/atom+xml"]
suffixes = ["xml"]
[mediaTypes."text/cloudflare"]
delimiter = ""

[minify]
minifyOutput = true
[minify.tdewolff.html]
keepDefaultAttrVals = false
keepQuotes = true
keepSpecialComments = false

[outputFormats]
[outputFormats.atom]
baseName = "atom"
mediaType = "application/atom+xml"
[outputFormats.rss]
baseName = "rss"
[outputFormats.headers]
baseName = "_headers"
isPlainText = true
mediatype = "text/cloudflare"
notAlternative = true

[outputs]
home = ["html", "rss", "atom"]
section = ["html", "rss", "atom"]

[params]
author = "tmash"
src = "https://github.com/7m45h/www_7m45h/tree/master/"

[security]
enableInlineShortcodes = true

[sitemap]
changefreq = "weekly"
