capitalizeListTitles = false
cleanDestinationDir = true
defaultContentLanguage = "en-us"
copyright = "AGPL-3.0 license"
disableKinds = ["RSS", "taxonomy", "term"]
enableGitInfo = true
enableRobotsTXT = true
languageCode = "en-us"
noChmod = true
noTimes = true
pluralizeListTitles = false
removePathAccents = true
timeout = "60s"
timeZone = "Etc/Universal"
title = "7m45h"

[build]
noJSConfigInAssets = true
useResourceCacheWhen = "always"
[build.buildStats]
enable = true

[minify]
minifyOutput = true
[minify.tdewolff.css]
keepCSS2 = false
[minify.tdewolff.html]
keepQuotes = true
[minify.tdewolff.js]
version = 0
[minify.tdewolff.json]
keepNumbers = true

[security]
enableInlineShortcodes = true

[sitemap]
changefreq = "weekly"

[params]
author = "tmash"
gitremote = "https://github.com/7m45h/www_7m45h/tree/master/"
